import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Providers from "./providers";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import NotificationProvider from "@/components/provider/NotificationProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// import { Inter } from "next/font/google";
// import Providers from "./providers";

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      // className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <NotificationProvider>
            <NavBar />
            {children}
            {/* <Toaster /> */}
            {/* <Toaster position="top-center" richColors /> */}
            <Toaster
              position="top-center"
              closeButton
              toastOptions={{
                style: {
                  borderRadius: "12px",
                  padding: "16px",
                },
                classNames: {
                  toast: "bg-white border border-gray-200 shadow-lg",
                  title: "text-sm font-semibold text-gray-900",
                  description: "text-sm text-gray-500",
                  actionButton: "bg-blue-600 text-white",
                  closeButton: "bg-white border-gray-200",
                  icon: "text-blue-600",
                },
              }}
            />
            <Footer />
          </NotificationProvider>
        </Providers>
      </body>
    </html>
  );
}
